
GET http://localhost:8000/predict
###

POST http://localhost:8000/crop-recommendation/suitable-crops
Content-Type: application/json

{"location": "balangoda, Sri Lanka", "use_defaults": true}

HTTP/1.1 200  - OK
date: Mon, 07 Jul 2025 16:56:32 GMT
server: uvicorn
content-length: 57
content-type: application/json
connection: close
###
POST http://localhost:8000/train
Content-Type: application/json
###
POST  http://127.0.0.1:8000/chat 
Content-Type: application/json

{
  "message": "what is quntumn computing?"
}

HTTP/1.1 200  - OK
date: Mon, 07 Jul 2025 18:36:03 GMT
server: uvicorn
content-length: 167
content-type: application/json
connection: close
###
POST http://localhost:8000/crop-recommendation/suitable-crops/manual
Content-Type: application/json

{
  "nitrogen": 90,
  "temperature": 23.75,
  "humidity": 82.32,
  "ph": 6.5,
  "rainfall": 200.98
}
###
POST http://localhost:8000/crop-recommendation/suitable-crops
Content-Type: application/json

{"location": "Mumbai, India", "use_defaults": true}
###
POST http://localhost:8000/crop-recommendation/suitable-crops/manual
Content-Type: application/json

{
  "nitrogen": 40,
  "temperature": 35,
  "humidity": 30,
  "ph": 7.5,
  "rainfall": 20
}